name: DeepDTAF_env
channels:
- pytorch
- https://repo.anaconda.com/pkgs/main
- pypi
- defaults
dependencies:
- pytorch=1.4.0
- cudatoolkit=10.1.243
- cudnn=7.6.0
- python=3.7.3
- numpy=1.16.4
- scikit-learn=0.21.2
- pandas=0.24.2
- tensorboard=2.0.0
- scipy=1.3.0
- numba=0.44.1
- tqdm=4.32.1
